// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6wh9foeQPswP8qbID0uYGbTjyrDZOaJY',
    appId: '1:902871814728:web:ab3eeefe3d1c45e37dbe7d',
    messagingSenderId: '902871814728',
    projectId: 'exemplo-firebase-c13f1',
    authDomain: 'exemplo-firebase-c13f1.firebaseapp.com',
    storageBucket: 'exemplo-firebase-c13f1.appspot.com',
    measurementId: 'G-3D28PDD3EM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPuB76sdJF_ovSkzFxWWoPEQ_v9XsVQos',
    appId: '1:902871814728:android:7a8b172778e41ef77dbe7d',
    messagingSenderId: '902871814728',
    projectId: 'exemplo-firebase-c13f1',
    storageBucket: 'exemplo-firebase-c13f1.appspot.com',
  );
}


